### ISSUE TITLE
please update the wiki for the following /etc/ctdb/ctdb.conf content

### ISSUE THREAD

**Issue by edylie** [gluster/storhaug#11]
CTDB_RECOVERY_LOCK=/run/gluster/shared_storage/.ctdb/reclock

# List of nodes in the cluster.  Default is below.
 CTDB_NODES=/etc/ctdb/nodes

# List of public addresses for providing NAS services.  No default.
 CTDB_PUBLIC_ADDRESSES=/etc/ctdb/public_addresses

# What services should CTDB manage?  Default is none.
# CTDB_MANAGES_SAMBA=yes
# CTDB_MANAGES_WINBIND=yes
 CTDB_MANAGES_NFS=yes

CTDB_NFS_CALLOUT=/etc/ctdb/nfs-ganesha-callout
CTDB_NFS_STATE_FS_TYPE=glusterfs
CTDB_NFS_STATE_MNT=/run/gluster/shared_storage
CTDB_NFS_SKIP_SHARE_CHECK=yes
NFS_HOSTNAME=localhost

**Comment by icebal** [comment]
Also, the example for  /etc/ctdb/public_addresses should have the mask attached, like so:

192.168.1.6/24 eth0
192.168.1.7/24 eth0
192.168.1.8/24 eth0
192.168.1.9/24 eth0

**Comment by kalebskeithley** [comment]
fixed public_addresses
