### ISSUE TITLE
storhaug support for multiple IPs/interfaces, choose which one to use

### ISSUE THREAD

**Issue by pasikarkkainen** [gluster/storhaug#15]
version: storhaug-nfs-1.0-1.el7.noarch

Currently storhaug ctdb nfs-ganesha-callout script hardcodes the following:

``
eval hostaddrs=( $(hostname -I) )
hostaddr="${hostaddrs[0]}"
``

This only works if there's only one IP/interface on the server. When there are multiple IPs/interfaces, one might want to use other than the first IP for ctdb/clustering/nfs-ganesha.

ctdb itself properly supports multiple IPs/interfaces, it's only storhaug nfs-ganesha-callout script which doesn't.

Maybe make the [0] index configurable with a parameter, so the user can specify which IP address to use?

**Comment by pasikarkkainen** [comment]
Or the ability to specify the network interface to use to get the IP from?

**Comment by kalebskeithley** [comment]
duplicate of https://github.com/gluster/storhaug/issues/8
