### ISSUE TITLE
error message not descriptive

### ISSUE THREAD

**Issue by jfarcher** [gluster/storhaug#3]
After just running storhaug setup as per the wiki, i was given the followin output:
Setting up
ERROR: num_servers != num_addrs

I can take a guess as to what it means, but not sure which area it is referring to.

**Comment by edylie** [comment]
hi jfarcher,

Did you manage to get this resolve? I am having the same error.

Thanks!

**Comment by jfarcher** [comment]
No still having the issue. I commented out the problematic lines in the script, I was planning on having a look why it breaks things just haven't had a chance.

**Comment by edylie** [comment]
Hello! Funny that is what i did as well. I commented out those offending lines

#        if [[ "${num_servers}" != "${num_addrs}" ]]; then
#            storlog "ERR" "num_servers != num_addrs"
#            return 1
#        fi

**Comment by kalebskeithley** [comment]
fixed in commit a3c325705d54d6f699ed6aa105fe652d9778d2c3
