### ISSUE TITLE
Logrotate for ganesha-gfapi.log

### ISSUE THREAD

**Issue by ryno83** [gluster/storhaug#33]
@kalebskeithley Do you think storhaug should create the logrotate config for ganesha-gfapi.log when invoking `storhaug setup` ? And remove it when teardown ?

**Comment by thotz** [comment]
The logrotate file is installed as part of nfs-ganesha-gluster package. 

# rpm -qil nfs-ganesha-gluster-2.7.0-1.el7.x86_64
Name        : nfs-ganesha-gluster
Version     : 2.7.0
Release     : 1.el7
Architecture: x86_64
Install Date: Tuesday 18 September 2018 10:03:37 AM IST
Group       : Applications/System
Size        : 88463
License     : LGPLv3+
Signature   : (none)
Source RPM  : nfs-ganesha-2.7.0-1.el7.src.rpm
Build Date  : Monday 17 September 2018 09:31:02 PM IST
Build Host  : df7dd86f28ad4228bb494d368a22b418
Relocations : (not relocatable)
URL         : https://github.com/nfs-ganesha/nfs-ganesha/wiki
Summary     : The NFS-GANESHA's GLUSTER FSAL
Description :
This package contains a FSAL shared object to
be used with NFS-Ganesha to support Gluster
/etc/logrotate.d/ganesha-gfapi
/usr/lib64/ganesha/libfsalgluster.so
/usr/lib64/ganesha/libfsalgluster.so.4
/usr/lib64/ganesha/libfsalgluster.so.4.2.0
/usr/share/man/man8/ganesha-gluster-config.8.gz

Are u checking for this ?

**Comment by ryno83** [comment]
I'm on debian stretch and the logrotate is missing.
**dpkg -c nfs-ganesha-gluster_2.7.0-1_amd64.deb**

drwxr-xr-x root/root         0 2018-09-21 07:51 ./
drwxr-xr-x root/root         0 2018-09-21 07:51 ./etc/
drwxr-xr-x root/root         0 2018-09-21 07:51 ./etc/ganesha/
-rw-r--r-- root/root       822 2018-09-21 07:51 ./etc/ganesha/gluster.conf
drwxr-xr-x root/root         0 2018-09-21 07:51 ./usr/
drwxr-xr-x root/root         0 2018-09-21 07:51 ./usr/lib/
drwxr-xr-x root/root         0 2018-09-21 07:51 ./usr/lib/x86_64-linux-gnu/
drwxr-xr-x root/root         0 2018-09-21 07:51 ./usr/lib/x86_64-linux-gnu/ganesha/
-rw-r--r-- root/root     85672 2018-09-21 07:51 ./usr/lib/x86_64-linux-gnu/ganesha/libfsalgluster.so
drwxr-xr-x root/root         0 2018-09-21 07:51 ./usr/share/
drwxr-xr-x root/root         0 2018-09-21 07:51 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-09-21 07:51 ./usr/share/doc/nfs-ganesha-gluster/
-rw-r--r-- root/root      6518 2018-09-21 07:40 ./usr/share/doc/nfs-ganesha-gluster/changelog.Debian.gz
-rw-r--r-- root/root      1299 2018-09-21 07:39 ./usr/share/doc/nfs-ganesha-gluster/copyright

I will close this issue and report it there https://github.com/gluster/glusterfs-debian

Thanks

**Comment by thotz** [comment]
IMO u need to open up issue in ganesha https://github.com/nfs-ganesha/nfs-ganesha/issues/ not in gluster

**Comment by kalebskeithley** [comment]
Looks like it's a packaging issue. https://github.com/nfs-ganesha/nfs-ganesha-debian/issues

**Comment by ryno83** [comment]
What is the purpose of the branch `stretch-nfs-ganesha` there https://github.com/gluster/glusterfs-debian ? I though the packaging of nfs-ganesha-gluster was the responsability of the Gluster team ! Sorry for the mess.
