### ISSUE TITLE
discussion about switch from pcs to ctdb

### ISSUE THREAD

**Issue by AmritasyaPutra** [gluster/storhaug#5]
What was the reason to switch from pcs to ctdb? I guess when ctdb manages vips then pcs cannot be used productively.

**Comment by kalebskeithley** [comment]
I guess by pcs you really mean pacemaker; pcs is just one interface to pacemaker.
You can still use pacemaker (for other things) but I think it would be fairly obvious that if ctdb is managing VIPs that you can't use pacemaker to manage those same VIPs.
Some of the reasons for the switch:
+ pacemaker is complex and difficult to debug
+ we found that pacemaker was "brittle" and failed in strange and unintuitive ways
+ pacemaker requires fencing agents (additional complexity)
+ users were asking for a solution that was easier to set up and maintain
+ the desire from the beginning was to provide a single solution for ganesha and samba, but samba users indicated they were unlikely to ever switch to pacemaker. They would have to run ctdb regardless.
+ probably others I can't think of at the moment.

**Comment by AmritasyaPutra** [comment]
I could not understand, isn't fencing a cluster requirement rather that specific to pcs? The pacemaker community seems to be very active and the project has long history. https://github.com/ClusterLabs and https://clusterlabs.org/developers.html Perhaps ctdb has other benefits.

**Comment by kalebskeithley** [comment]
Sure, all true.

You are certainly welcome to write your own HA solution using pacemaker and even host it here at github/gluster if you want.

But storhaug is based on ctdb.
