### ISSUE TITLE
different IP?

### ISSUE THREAD

**Issue by edylie** [gluster/storhaug#9]
we have 3 nodes glusterfs and each node has 2 IP 172.16.16.x (management) and 192.168.0.x(CTDB,NFS,GLUSTERFS)

When I used the storhaug setup, it would automatically create entry based on my management IPs

[root@gluster-1683 nfs-ganesha]# pwd
/run/gluster/shared_storage/nfs-ganesha

[root@gluster-1683 nfs-ganesha]# ls -al
total 29
drwxr-xr-x 7 root root 4096 Aug  5 15:53 .
drwxr-xr-x 4 root root 4096 Aug  5 15:39 ..
drwxr-xr-x 4 root root 4096 Aug  5 15:39 172.16.16.130
drwxr-xr-x 4 root root 4096 Aug  5 15:44 172.16.16.131
drwxr-xr-x 4 root root 4096 Aug  5 15:44 172.16.16.132
drwxr-xr-x 2 root root 4096 Aug  5 15:47 exports
-rw-r--r-- 1 root root   75 Aug  5 15:52 ganesha.conf
drwxr-xr-x 2 root root 4096 Aug  5 15:59 .noderefs
[root@gluster-1683 nfs-ganesha]#

[root@gluster-1683 nfs-ganesha]# cd 172.16.16.130/
[root@gluster-1683 172.16.16.130]# ls -al
total 16
drwxr-xr-x 4 root root 4096 Aug  5 15:39 .
drwxr-xr-x 7 root root 4096 Aug  5 15:53 ..
drwxr-xr-x 4 root root 4096 Aug  5 15:46 ganesha
drwxr-xr-x 4 root root 4096 Aug  5 15:46 statd
-rw-r--r-- 1 root root    0 Aug  5 15:47 state

[root@gluster-1683 172.16.16.130]# cd ganesha/
[root@gluster-1683 ganesha]# ls -al
total 16
drwxr-xr-x 4 root root 4096 Aug  5 15:46 .
drwxr-xr-x 4 root root 4096 Aug  5 15:39 ..
lrwxrwxrwx 1 root root   71 Aug  5 15:46 172.16.16.131 -> /run/gluster/shared_storage/nfs-ganesha/.noderefs/172.16.16.131/ganesha
lrwxrwxrwx 1 root root   71 Aug  5 15:46 172.16.16.132 -> /run/gluster/shared_storage/nfs-ganesha/.noderefs/172.16.16.132/ganesha
lrwxrwxrwx 1 root root   71 Aug  5 15:46 192.168.0.252 -> /run/gluster/shared_storage/nfs-ganesha/.noderefs/192.168.0.252/ganesha
lrwxrwxrwx 1 root root   71 Aug  5 15:46 192.168.0.253 -> /run/gluster/shared_storage/nfs-ganesha/.noderefs/192.168.0.253/ganesha
lrwxrwxrwx 1 root root   71 Aug  5 15:46 192.168.0.254 -> /run/gluster/shared_storage/nfs-ganesha/.noderefs/192.168.0.254/ganesha
drwxr-xr-x 3 root root 4096 Aug  5 15:39 v4old
drwxr-xr-x 3 root root 4096 Aug  5 15:39 v4recov

anyone know why it created based on 172.16.16.x IPs? how do i remove it?

**Comment by icebal** [comment]
looks like it is done in the nfs-ganesha-callout script. its using hostname -I to grab all the IPs, and then creates the directories. below is it setting the variables, and in the function create_ganesha_recdirs () it runs through and does a mkdir -p on NODESTATEDIR along with all the dir under it.

it looks like to remove them, you either need storhaug to go config file based, or allow it to override by env or flag :/

       eval hostaddrs=( $(hostname -I) )
        hostaddr="${hostaddrs[0]}"
        NODESTATEDIR="${state_dir}/nfs-ganesha/${hostaddr}"
        GANSTATEDIR="${state_dir}/nfs-ganesha/.noderefs"
        NODESTATELN="${GANSTATEDIR}/${hostaddr}"

**Comment by edylie** [comment]
I got it fixed by editing 

vi /etc/ctdb/nfs-ganesha-callout and set this 

hostname -I | awk '{print $2}'

So it would use my secondary IP for building out the config.

**Comment by kalebskeithley** [comment]
I'm not sure what you mean by "go config file based" 

AFAIK CTDB should be creating VIPs from the IP addrs configured in /etc/ctdb/public_addresses.
There may be other ways to run CTDB, but I'm only familiar with, and am only supporting, what's outlined here in the storhaug wiki.

There is an issue with the `hostname -I` on systems that use gnu inetutils hostname. I only know about arch linux that uses inetutils. Debian, Fedora, RHEL, CentOS, Ubuntu all use Debian's hostname pkg sources which still has -I.

**Comment by edylie** [comment]
Sorry i was not being clear. When i used this hostname -I in the ganesha call out script it would create entries in the gluster shared storage for both of my ips. I have 2 interfaces.

**Comment by kalebskeithley** [comment]
I consider this the same as issue #8. When our resident ctdb expert returns from vacation I'll pick his brain because I'm not seeing how Samba has solved this. Closing this for now. We can reopen if necessary.
